# Purpose of this notebook
- Learn tensorflow mathematical operations

In [1]:
import tensorflow as tf

# tf.add

In [6]:
x = tf.constant([1, 2, 3])
y = tf.constant([40, 50, 60])
z = tf.add(x, y)
print(z)

tf.Tensor([41 52 63], shape=(3,), dtype=int32)


# tf.subtract

In [5]:
x = tf.constant([1, 2, 3])
y = tf.constant([40, 50, 60])
z = tf.subtract(x, y)
print(z)

tf.Tensor([-39 -48 -57], shape=(3,), dtype=int32)


# tf.divide

In [7]:
x = tf.constant([1, 2, 3])
y = tf.constant([40, 50, 60])
z = tf.divide(y, x)
print(z)

tf.Tensor([40. 25. 20.], shape=(3,), dtype=float64)


# tf.multiply

In [8]:
x = tf.constant([1, 2, 3])
y = tf.constant([40, 50, 60])
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 40 100 180], shape=(3,), dtype=int32)


# tf.tensordot

In [9]:
x = tf.constant([1, 2, 3])
y = tf.constant([40, 50, 6])
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(158, shape=(), dtype=int32)


# tf.pow

In [11]:
x = tf.constant([1, 2, 3])
print(tf.pow(x, 2))

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


# tf.matmul

In [19]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[ 2.1261983  4.6701736  5.136496   2.8316314]
 [-2.5273232 -2.915297  -3.2464776 -2.1930473]], shape=(2, 4), dtype=float32)
