# Purpose of this notebook
- Learn tensorflow indexing

In [1]:
import tensorflow as tf

# animals

In [4]:
animals = [
    "Antelope", "Bear", "Cat", "Dolphin", "Elephant", "Fox", "Giraffe",
    "Hippopotamus", "Iguana", "Jaguar", "Kangaroo", "Lion", "Monkey",
    "Newt", "Owl", "Penguin", "Quokka", "Rabbit", "Snake", "Tiger",
    "Urial", "Vulture", "Whale", "Xerus", "Yak", "Zebra"
]

In [2]:
from typing import Any

# slice

In [10]:

x: Any = tf.constant(animals)
print(x[:])

tf.Tensor(
[b'Antelope' b'Bear' b'Cat' b'Dolphin' b'Elephant' b'Fox' b'Giraffe'
 b'Hippopotamus' b'Iguana' b'Jaguar' b'Kangaroo' b'Lion' b'Monkey' b'Newt'
 b'Owl' b'Penguin' b'Quokka' b'Rabbit' b'Snake' b'Tiger' b'Urial'
 b'Vulture' b'Whale' b'Xerus' b'Yak' b'Zebra'], shape=(26,), dtype=string)


In [11]:

x: Any = tf.constant(animals)
print(x[1:])

tf.Tensor(
[b'Bear' b'Cat' b'Dolphin' b'Elephant' b'Fox' b'Giraffe' b'Hippopotamus'
 b'Iguana' b'Jaguar' b'Kangaroo' b'Lion' b'Monkey' b'Newt' b'Owl'
 b'Penguin' b'Quokka' b'Rabbit' b'Snake' b'Tiger' b'Urial' b'Vulture'
 b'Whale' b'Xerus' b'Yak' b'Zebra'], shape=(25,), dtype=string)


In [5]:
x: Any = tf.constant(animals)
print(x[1:3])

tf.Tensor([b'Bear' b'Cat'], shape=(2,), dtype=string)


# step 2

In [6]:
x: Any = tf.constant(animals)
print(x[::2])

tf.Tensor(
[b'Antelope' b'Cat' b'Elephant' b'Giraffe' b'Iguana' b'Kangaroo' b'Monkey'
 b'Owl' b'Quokka' b'Snake' b'Urial' b'Whale' b'Yak'], shape=(13,), dtype=string)


# Reverse

In [7]:
x: Any = tf.constant(animals)
print(x[::-1])

tf.Tensor(
[b'Zebra' b'Yak' b'Xerus' b'Whale' b'Vulture' b'Urial' b'Tiger' b'Snake'
 b'Rabbit' b'Quokka' b'Penguin' b'Owl' b'Newt' b'Monkey' b'Lion'
 b'Kangaroo' b'Jaguar' b'Iguana' b'Hippopotamus' b'Giraffe' b'Fox'
 b'Elephant' b'Dolphin' b'Cat' b'Bear' b'Antelope'], shape=(26,), dtype=string)


# 2D

In [8]:
x: Any = tf.constant([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
])
print(x[0, ::-1])

tf.Tensor([5 4 3 2 1], shape=(5,), dtype=int32)


In [12]:
x: Any = tf.constant([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
])
print(x[::-1, 2:4])

tf.Tensor(
[[8 9]
 [3 4]], shape=(2, 2), dtype=int32)
