# Purpose of this notebook
- Learn tensorflow reshaping

In [2]:
import tensorflow as tf

# tf.reshape

In [4]:
x = tf.range(10)
y = tf.reshape(x, (2, 5))
print(x)
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)


# tf.transpose

In [6]:
x = tf.range(10)
y = tf.reshape(x, (2, 5))
z = tf.transpose(y)
print(y)
print(z)

tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]], shape=(5, 2), dtype=int32)
