# Purpose of this notebook
- Learn to init tensor using tensorflow

# Import
- Before using tensorflow, we need to import it

In [1]:
import tensorflow as tf

In [ ]:
x = tf.constant(4)
print(x)

In [ ]:
x = tf.constant(4.0)
print(x)

# Implicit dtype
- notice that `4` will result `dtype=int32`
- notice that `4.0` will result `dtype=float32`

# Explicit shape

In [10]:
x = tf.constant(4, shape=(1, 1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


# Explicit dtype

In [11]:
x = tf.constant(4, dtype=tf.float32)
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


# Nested array

In [12]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# tf.ones

In [13]:
x = tf.ones((2, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


# tf.zeros  

In [14]:
x = tf.zeros((2, 3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# tf.eye
- I for identity matrix

In [15]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


# tf.range

In [16]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


# tf.range

In [21]:
x = tf.range(start=1, limit=11, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


# tf.random.normal

In [18]:
x = tf.random.normal((2, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.14399523  1.2897618  -0.36424723]
 [ 0.50024134 -1.0311455  -1.0337405 ]], shape=(2, 3), dtype=float32)


# tf.random.uniform

In [19]:
x = tf.random.uniform((2, 3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.31880248 0.52137005 0.76204157]
 [0.11930776 0.23367226 0.19460702]], shape=(2, 3), dtype=float32)


# tf.cast

In [22]:
x = tf.range(10)
print(x)
y = tf.cast(x, dtype=tf.float32)
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)
