# Purpose of this notebook
- Use keras sequential API to solve fashion_mnist

# Import

In [1]:
from tensorflow import keras # type: ignore
from tensorflow.keras import layers # type: ignore
from tensorflow.keras.datasets import fashion_mnist # type: ignore

# Load data

In [2]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 7s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


# Reshape

In [3]:
x_train = x_train.reshape(-1, 28*28)
x_test = x_test.reshape(-1, 28*28)
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


# Before normalize, range in [0, 255]

In [4]:
print(x_train[0, 190:195])
print(x_test[0, 245:250])

[ 64  23  77 130  72]
[  0   0   0   0 119]


# Normalize
- Note: Run following cell only once

In [5]:
x_train = x_train / 255
x_test = x_test / 255

# After normalize, range in [0, 1]

In [6]:
print(x_train[0, 190:195])
print(x_test[0, 245:250])

[0.25098039 0.09019608 0.30196078 0.50980392 0.28235294]
[0.         0.         0.         0.         0.46666667]


# Keras Sequential API

In [7]:
model = keras.Sequential([
    keras.Input(shape=(28*28,)),
    layers.Dense(512, activation='relu', name='first_layer'),
    layers.Dense(256, activation='relu', name='second_layer'),
    layers.Dense(10, name='output_layer'),
], name="sequential_model")

# model.summary 

In [8]:
print(model.summary())

Model: "sequential_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ first_layer (Dense)             │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ second_layer (Dense)            │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

None


# model.compile

In [9]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

# Note
- If output layer `layers.Dense(10)` then use `from_logits=True`
- If output layer `layers.Dense(10, activation='softmax')` then use `from_logits=False`, or just simply remove `from_logits=False`

# Train the model using model.fit

In [10]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

Epoch 1/5
1875/1875 - 5s - 3ms/step - accuracy: 0.8294 - loss: 0.4691
Epoch 2/5
1875/1875 - 4s - 2ms/step - accuracy: 0.8668 - loss: 0.3571
Epoch 3/5
1875/1875 - 4s - 2ms/step - accuracy: 0.8798 - loss: 0.3223
Epoch 4/5
1875/1875 - 4s - 2ms/step - accuracy: 0.8887 - loss: 0.2983
Epoch 5/5
1875/1875 - 4s - 2ms/step - accuracy: 0.8958 - loss: 0.2795


# Evaluate test data using model.evaluate

In [11]:
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.8664 - loss: 0.3700


[0.37002992630004883, 0.8664000034332275]